app = "tdairad-dicoogle"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  REPORTING_WEBHOOK_URL = "https://tdairad-api.fly.dev/webhook/study"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 104
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 104

[[mounts]]
  source = "dicoogle_data"
  destination = "/var/dicoogle/storage"
